---
- name: Base pre
  hosts: all
  roles:
    - emit-job-header
    - log-inventory
    - add-build-sshkey
    - start-zuul-console
    - validate-host
    - prepare-workspace-log
    - ensure-output-dirs-present
    - diagnose-first-sudo
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: yes
